### PR TITLE
Ability to get the last response

### LINKED ISSUE #358: Access response headers to get x-rate-limit header values
I was using the 2.x version of this library and I have a situation where I am making lots of requests to `getUserTimeline()` and I want to know when I am close to hitting the rate limit so I can sleep and wait for the rate limit to reset. I want to sleep **before** I hit the rate limit so that I can leave some api calls available for other services.

In the 2.x version I was able to do something like this:
```php
foreach ($screenNames as $screenName) {
    $timeline = $twitter->getUserTimeline(['screen_name' => $screenName]);
    
    // do something with the timeline
    
    // check if close to rate limit
    $headers = $twitter->response['headers'];
    $rateLimitRemaining = Arr::get($headers, 'x-rate-limit-remaining', 0);
    if ($rateLimitRemaining < 50) {
        $timestamp = Arr::get($headers, 'x-rate-limit-reset', 0);
        $secondsUntilReset = max($timestamp - time(), 0);
        sleep($secondsUntilReset);
    }
}
```

This works because I am able to access the previous response and headers.

I am aware of `getAppRateLimit()` but it seems wasteful to make an extra API call given that each response includes the `x-rate-limit-*` headers. I could catch the `RateLimitedException` but at that point it is too late since I want to sleep **before** I hit the rate limit.

Would you be open to storing the last response like it did in the 2.x version? If so which object would be the best place to store it? I wonder if this could cause a race condition, if you make a request and then before you can access the previous response another request is made so you are not getting the response that you intended.

Alternatively, after each request it may be possible to cache the rate limit values per resource in a format similar to the response from `getAppRateLimit()`
```php
[
    "/statuses/user_timeline" => [
           "limit" => 900,
           "remaining" => 899,
           "reset" => 1621035809,
     ]
]
```
then you could get the rate limit values without having to make a separate API call using `getAppRateLimit()`

If that seems like overkill then I may resort to calling `getAppRateLimit()` after every X requests to see if I am close to hitting the rate limit.

Another idea would be to have a config value and when the `x-rate-limit-remaining` header value was less than the configured value it would throw a `CloseToRateLimitException`

### PR DESCRIPTION
**Pull request by ejunker**
Fixes #358 

Added a `getSyncClient()` method to `Querier` and added a `getResponse()` method to `SyncClient`. This allows you to access the last response including the headers.

I did not add anything to `AsyncClient` since I wasn't sure how that would work since it returns a Promise.
I wasn't sure the best way to update the tests so let me know if I should change anything. I wanted to test that the response is still set when there is an exception but couldn't figure out how to test that with the mocked objects.

### CODE REVIEW

File: src/Contract/Http/SyncClient.php [hunk 1]
```diff
@@ -13,4 +14,9 @@ interface SyncClient extends Client
      * @throws ClientException
      */
     public function request(string $method, string $url, array $data = []);
+
+    /**
+     * @return ResponseInterface|null
+     */
+    public function getResponse();
```
Comment (reliq) [inline src/Contract/Http/SyncClient.php:21]:
```suggestion
    public function getLastResponse();
```

File: tests/Unit/Service/QuerierTest.php [hunk 2]
```diff
@@ -144,6 +144,7 @@ public function testQuery(): void
         $result = $this->subject->query($endpoint, $method, $params, $multipart, $extension);
 
         self::assertSame($response, $result);
+        self::assertInstanceOf(SyncClient::class, $this->subject->getSyncClient());
```
Comment (reliq) [inline tests/Unit/Service/QuerierTest.php:147]: We don't need this assertion since the method is a type-hinted getter.

```suggestion
```

File: src/Contract/Querier.php [hunk 3]
```diff
@@ -105,4 +106,6 @@ public function delete(string $endpoint, array $parameters = []);
     public function getStream(string $endpoint, callable $onData, array $parameters = []): void;
 
     public function getConfiguration(): Configuration;
+
+    public function getSyncClient(): SyncClient;
```
Comment (reliq) [inline src/Contract/Querier.php:110]: I'd also add `getAsyncClient()` for completeness sake.

**Review by reliq — CHANGES_REQUESTED** [review]
Looks good @ejunker, only a few suggestions.

Thank you for contributing 😄

**Comment by ejunker** [comment]
@reliq  made the suggested changes. Renamed `getResponse()` to `getLastResponse()` and added `getAsyncClient()`

**Review by reliq — APPROVED** [review]

**Review by atymic — APPROVED** [review]

**Comment by atymic** [comment]
Thanks for the PR @ejunker and thanks for the review @reliq  :)
